source 'https://rubygems.org'
ruby '2.3.0'

gem 'autoprefixer-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'devise_token_auth'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'omniauth'
gem 'pg'
gem 'rails', '4.2'
gem 'rails-api'
gem 'sass-rails', '~> 4.0.2'
gem 'webmock'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'database_cleaner'
  gem 'hologram'
  gem 'launchy'
  gem 'poltergeist'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
end
